#!/usr/bin/env node
/**
 * Generate frontend/generated/notifications.ts from Steam's published protobuf.
 *
 * Hand-maintaining this was wrong twice over: the enum drifted six values behind
 * (ControllerConnected and friends fire routinely), and routing by field
 * position read the wrong field for messages that declare an id second --
 * Achievement puts achievement_id before appid, and FriendMessage stores its
 * steamid as a string rather than the fixed64 every other message uses.
 *
 * Run `npm run gen` after refreshing vendor/steammessages_clientnotificationtypes.proto.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseProto } from './proto.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const PROTO = join(root, 'vendor', 'steammessages_clientnotificationtypes.proto');
const OUT = join(root, 'frontend', 'generated', 'notifications.ts');

const { types, messages } = parseProto(readFileSync(PROTO, 'utf8'));

// Enum value FriendOnline pairs with message CClientNotificationFriendOnline.
// Twenty-one values carry no message at all, which correctly means no payload
// and therefore no route.
const typeToMessage = {};
for (const { name, index } of types) {
	const candidate = `CClientNotification${name}`;
	if (messages[candidate]) typeToMessage[index] = candidate;
}

const banner = `// GENERATED by tools/gen-proto.mjs from
// vendor/steammessages_clientnotificationtypes.proto
//
// Do not edit. Run \`npm run gen\` instead.
//
// Source: SteamDatabase/SteamTracking, cited by Millennium's own SteamClient
// typings as the origin of these definitions.
`;

const out = `${banner}
export interface ProtoField {
	name: string;
	type: string;
}

/** EClientNotificationType index to its short name. */
export const NOTIFICATION_TYPE_NAMES: Record<number, string> = ${JSON.stringify(
	Object.fromEntries(types.map((t) => [t.index, t.name])),
	null,
	'\t',
)};

/** Message name to its fields, keyed by protobuf field number. */
export const MESSAGE_FIELDS: Record<string, Record<number, ProtoField>> = ${JSON.stringify(
	messages,
	null,
	'\t',
)};

/** Notification type index to the message that carries its payload. */
export const TYPE_TO_MESSAGE: Record<number, string> = ${JSON.stringify(
	typeToMessage,
	null,
	'\t',
)};

export function typeName(type: number): string {
	return NOTIFICATION_TYPE_NAMES[type] ?? \`Unknown(\${type})\`;
}

/** Field names for a notification type, or null when it carries no payload. */
export function fieldsForType(type: number): Record<number, ProtoField> | null {
	const message = TYPE_TO_MESSAGE[type];
	return message ? MESSAGE_FIELDS[message] ?? null : null;
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);

console.log(
	`generated ${OUT}\n` +
		`  ${types.length} enum values (max index ${Math.max(...types.map((t) => t.index))})\n` +
		`  ${Object.keys(messages).length} messages\n` +
		`  ${Object.keys(typeToMessage).length} types with a payload message`,
);
